version: '3.8'

services:
  app:
    build: .
    container_name: node-app
    ports:
      - "80:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always
    networks:
      - app-network
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: "3306"
    command: sh -c "until nc -z db 3306; do echo '⏳ Waiting for MySQL...'; sleep 2; done && npm start"

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"  # This is still fine for external access
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
